name: x86_64Lite

on:
  repository_dispatch:
  workflow_dispatch:

env:
  IPNAME: 'x86_64Lite'
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: v23.05.4
  FEEDS_CONF: feeds.conf.default
  #EXTERNAL_FILE: configs/luci/Lite.config
  #CONFIG_FILE: configs/x86_64.config
  CONFIG_FILE: configs/amlogic
  SYS_CONF_SH: configure.sh
  PACKS: package.sh
  EXTEND_DRIVER: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: big

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    # - name: Initialization environment
    #   env:
    #     DEBIAN_FRONTEND: noninteractive
    #   run: |
    #     ARCH=$(uname -m)
    #     if [[ "$ARCH" == "x86_64" || "$ARCH" == "amd64" || "$ARCH" == "i386" || "$ARCH" == "i686" ]]; then
    #       sudo -E apt-get update
    #       sudo -E apt-get install -y $(curl -fsSL https://raw.githubusercontent.com/SFGZS888/ImmortalWrtBuilder/refs/heads/main/env-amd64)
    #     fi

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH immortalwrt
        ln -sf ./immortalwrt $GITHUB_WORKSPACE/immortalwrt

    - name: Cache
      uses: stupidloud/cachewrtbuild@main
      with:
          ccache: 'true'
          toolchain: 'true'
          mixkey: 'x86'
          prefix: 'immortalwrt'

    - name: Load custom feeds
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF immortalwrt/feeds.conf.default
        chmod +x $SYS_CONF_SH
        cd immortalwrt
        $GITHUB_WORKSPACE/$SYS_CONF_SH

    - name: Update feeds
      run: cd immortalwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd immortalwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && mv files immortalwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE immortalwrt/.config
        chmod +x $PACKS
        cd immortalwrt
        $GITHUB_WORKSPACE/$PACKS

    #- name: Extend Driver
      #if: env.EXTEND_DRIVER == 'true'
      #run: |
        $cat configs/Driver.config >> immortalwrt/.config

    - name: Modify configuration
      run: |
        cat $EXTERNAL_FILE >> immortalwrt/.config
        export FORCE_UNSAFE_CONFIGURE=1
        cd immortalwrt && make defconfig
        sed -i '/CONFIG_DEFAULT_luci/d' .config
        cat .config

    - name: Download package
      id: package
      run: |
        cd immortalwrt
        export FORCE_UNSAFE_CONFIGURE=1
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd immortalwrt
        echo -e "$(nproc) thread compile"
        export FORCE_UNSAFE_CONFIGURE=1
        IGNORE_ERRORS=m make -j$(nproc) clean world
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: immortalwrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: immortalwrt/bin

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd immortalwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: immortalwrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "== Timeï¼š$(date +'%Y-%m-%d %H:%M:%S') =="
        echo "release_tag=$(date +"%Y.%m.%d-%H%M%S")" >> $GITHUB_OUTPUT
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Generate release body
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        echo "![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ steps.tag.outputs.release_tag }}/total?style=flat-square)" >> release.txt

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: ${{ env.IPNAME }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
